version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: trade_pg
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: trades
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d trades"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pg_data: